routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\SeriesController;
use \App\Http\Controllers\SeasonsController;
use \App\Http\Controllers\EpisodesController;
use \App\Http\Controllers\LoginController;
use \App\Http\Controllers\UserController;
use \App\Http\Middleware\Autenticador;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect('/series');
// })->middleware(Autenticador::class);

Route::middleware([Autenticador::class])->group(function() {
    Route::get('/', function () {
        return redirect('/series');
    });

    Route::resource('/series', SeriesController::class)->except(['show']);

    Route::get('/series/{series}/seasons', [SeasonsController::class, 'index'])->name('seasons.index');

    Route::get('/seasons/{seasons}/episodes', [EpisodesController::class, 'index'])->name('episodes.index');

    Route::post('/seasons/{seasons}/episodes', [EpisodesController::class, 'update'])->name('episodes.update');

});
Route::get('/login',[LoginController::class, 'index'])->name('login');

Route::post('/login', [LoginController::class, 'store'])->name('signin');

Route::get('/register',[UserController::class, 'create'])->name('users.create');

Route::post('/register',[UserController::class, 'store'])->name('users.store');

Route::get('/logout',[LoginController::class, 'destroy'])->name('logout');

app/Models/Episode.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Episode extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['number'];


    public function seasons()
    {
        return $this->belongsTo(Seasons::class);
    }


}

app/Models/Seasons.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Seasons extends Model
{
    use HasFactory;
    
    protected $fillable = ['number'];
    // protected $table = 'seasons';

    public function series()
    {
        return $this->belongsTo(Series::class);
    }

    public function episodes()
    {
        return $this->hasMany(Episode::class);
    }
}

app/Models/Series.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Series extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];


    public function seasons()
    {
        return $this->hasMany(Seasons::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EpisodesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\SeasonsController;
use App\Models\Series;
use App\Models\Seasons;
use App\Models\Episode;

use Illuminate\Http\Request;

class EpisodesController extends Controller
{
    public function index(Seasons $seasons)
    {
        return view('episodes.index', [
            'episodes' => $seasons->episodes,
            'mensagemSucesso' => session('mensagem.sucesso')
        ]);
    }

    public function update(Request $request, Seasons $seasons)
    {
        
        $watchedEpisodes = $request->episodes;
        $seasons->episodes->each(function (Episode $episode) use ($watchedEpisodes) {
            $episode->watched = in_array($episode->id, $watchedEpisodes);
        });

        $seasons->push();

        return redirect()->route('episodes.index', $seasons->id)->with('mensagem', "series adicionada com sucesso");
    }

}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function index()
    {
        return view('login.index');
    }
    public function store(Request $request)
    {
        if (!Auth::attempt($request->only(['email', 'password']))) {
        return redirect()->back()->withErrors('Usuário ou senha inválidos');
        }
        return redirect()->route('series.index');
    }

    public function destroy()
    {
        Auth::logout();
        return redirect()->route('login');
    }

}

app/Http/Controllers/SeasonsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\SeriesFormRequest;
use App\Models\Series;
use App\Models\Seasons;
use App\Models\Episode;
use \App\Http\Controllers\SeriesController;
use \App\Http\Controllers\EpisodesController;




class SeasonsController extends Controller
{
    public function index(Series $series)
    {
        // dd($series);
        $seasons = $series->seasons()->with('episodes')->get();

        return view('seasons.index')->with('seasons', $seasons)->with('series', $series);
    }
}

app/Http/Controllers/SeriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\SeriesFormRequest;
use App\Models\Series;
use App\Models\Seasons;
use App\Models\Episode;
use \App\Http\Controllers\SeasonsController;
use Illuminate\Support\Facades\Mail;
use App\Mail\SeriesCreated;
use App\Models\User;
use App\Events\SeriesCreatedEvent;

use App\Repositories\SeriesRepository;
use Illuminate\Support\Facades\DB;

class SeriesController extends Controller
{
    public function index(Request $request)
    {
        $series = Series::query()->orderBy('name')->get();
        $mensagemSucesso = session()->get('mensagem');


        return view('series.index')->with('series', $series)->with('mensagemSucesso', $mensagemSucesso);
    }

    public function create()
    {
        return view('series.create');
    }

    public function store(SeriesFormRequest $request, SeriesRepository $repository)
    {  
        $series = $repository->add($request);
        SeriesCreatedEvent::dispatch(
            $series->name,
            $series->id,
            $request->seasonsQty,
            $request->episodesPerSeason);




        return redirect()->route('series.index')->with('mensagem', "series adicionada com sucesso");
    }

    public function destroy(Series $series)
    {
        $series->delete();

        return redirect()->route('series.index')->with('mensagem', "series '{$series->name}'excluida com sucesso");
    }

    public function edit (Series $series) 
    {
        return view('series.edit')->with('series', $series);
    }

    public function update(Series $series, SeriesFormRequest $request)
    {
        $series->fill($request->all());
        $series->save();

        return redirect()->route('series.index')->with('mensagem', "series '{$series->name}' Atualizada com sucesso");
    }

    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function create()
    {
        return view('users.create');
    }

    public function store(Request $request)
    {
        $data = $request->except(['_token']);
        $data['password'] = Hash::make($data['password']);

        $user = User::create($data);
        Auth::login($user);

        return redirect()->route('series.index');
    }

}

resources/views/episodes/index.blade.php
<x-layout title="Episódios" >
  <form method="post">
        @csrf
        <ul class="list-group">
          @foreach ($episodes as $episode)
              <li class="list-group-item d-flex justify-content-between align-items-center">
                  Episódio {{ $episode->number }}

                  <input type="checkbox"
                          name="episodes[]"
                          value="{{ $episode->id }}"
                           @if ($episode->watched) checked @endif />
              </li>
          @endforeach
        </ul>

        <button class="btn btn-primary mt-2 mb-2">Salvar</button>
    </form>
    <a href="{{route('series.index')}}" type="button" class="btn btn-dark badge mt-3">Voltar</a>
</x-layout>

resources/views/login/index.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="">

  <div class="container text-center">
    <h1>Login</h1>
      <form method="post">
        @csrf
        <div class="form-group">
          <label for="email" class="  form-label">Email</label>
          <input type="email" class=" form-control" id="email" name="email">
        </div>
        <div class="form-group">
          <label for="password" class="  form-label">Senha</label>
          <input type="password" class=" form-control" id="password" name="password">
        </div>
        <button class="btn btn-primary mt-3">
          Entrar
        </button>
      </form>
      <a href="{{ route('users.create') }}" class="btn btn-secondary mt-3">
        Registrar-se
      </a>
  
  </div>

</body>
</html>

resources/views/seasons/index.blade.php
<x-layout title="Temporadas de {!!$series->name!!}">

    <ul class="list-group">
        @foreach ($seasons as $season)
        <li class="list-group-item d-flex justify-content-between aling-itens-center">
            <a href="{{route('episodes.index', $season->id)}}">
                Temporada {{ $season->number }}
            </a>

            <span class="badge bg-secondary">

                 {{ $season->episodes->filter(fn ($episode) => $episode->watched)->count() }} /{{$season->episodes->count()}}

            </span>
        
        </li>

        @endforeach
    </ul>
     <a href="{{route('series.index')}}" type="button" class="btn btn-dark badge mt-3">Voltar</a>

</x-layout>

resources/views/series/create.blade.php
<x-layout title="Nova Série">
    <form action="{{ route('series.store') }}" method="POST">
  @csrf
  <div class="row mb-3">
    <div class="mb-3 col-8">
        <label for="name" class="form-label">Nome:</label>
        <input type="text" autofocus id="name" name="name" class="form-control" >
    </div>

    <div class="mb-3 col-2">
        <label for="seasonsQty" class="form-label">N Temporadas:</label>
        <input type="text" id="seasonsQty" name="seasonsQty" class="form-control">
    </div>

    <div class="mb-3 col-2">
        <label for="episodesPerSeason" class="form-label">Eps/ temporadas:</label>
        <input type="text" id="episodesPerSeason" name="episodesPerSeason" class="form-control" >
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Adicionar</button>
</form>
<a href="{{route('series.index')}}" type="button" class="btn btn-dark badge mt-3">Voltar</a>
</x-layout>

resources/views/series/edit.blade.php
<x-layout title="Editar Série {!!$series->name!!}">
    <x-series.form :action="route('series.update', $series->id)" :name="$series->name" />
    <a href="{{route('series.index')}}" type="button" class="btn btn-dark badge mt-3">Voltar</a>
</x-layout>

resources/views/series/index.blade.php
<x-layout title="Séries">
    <a href="{{route('series.create')}}" type="button" class="btn btn-dark mb-3">Adicionar</a>

    @isset($mensagemSucesso)

    <div class="alert alert-success">
        {{ $mensagemSucesso }}
    </div>

    @endisset

    <ul class="list-group">
        @foreach ($series as $serie)
        <li class="list-group-item d-flex justify-content-between aling-itens-center">
            <a href="{{route('seasons.index', $serie->id)}}">{!! $serie->name !!}</a>

        <span class="d-flex">

            <a type="button" href="{{ route('series.edit', $serie->id) }}" class="btn btn-primary btn-sm">E</a>     
            <form action="{{ route('series.destroy', $serie->id) }}" method="POST" class="ms-2">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger btn-sm">
                X
                </button>

            </form>
        </span>
        
        </li>

        @endforeach
    </ul>

</x-layout>

resources/views/users/create.blade.php
<x-layout title="Novo usuário">
    <form method="post">
        @csrf
        <div class="form-group">
            <label for="name" class="form-label">Nome</label>
            <input type="text" name="name" id="name" class="form-control">
        </div>

        <div class="form-group">
            <label for="email" class="form-label">E-mail</label>
            <input type="email" name="email" id="email" class="form-control">
        </div>

        <div class="form-group">
            <label for="password" class="form-label">Senha</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <button class="btn btn-primary mt-3">
            Registrar
        </button>
    </form>
</x-layout>